### ISSUE TITLE
[DOC] Dead link to RoboNeuro

### ISSUE THREAD

**Issue by mathdugre** [neurolibre/docs.neurolibre.com#52]
[This section](https://docs.neurolibre.org/en/latest/FAQ.html#how-can-i-test-a-neurolibre-submission) of the documentation refers to RoboNeuro. However, the link points to a Heroku app which no longer seems in service.

**Comment by agahkarakuzu** [comment]
Thanks @mathdugre for reporting it! 

We are migrating that service to https://robo.neurolibre.org. Soon we will push a major update to the documentation as we are moving to a new format (MyST instead of JupyterBook) for hosting living preprints.

Our preview binderhub has also moved to: https://binder-preview.conp.cloud/

**Comment by mathdugre** [comment]
Hi @agahkarakuzu , thank you for the quick response. I'll look over the new method

**Comment by agahkarakuzu** [comment]
I added a small documentation to https://github.com/neurolibre/mystical-article (README file)
